# Generated by Django 2.2.28 on 2022-06-07 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0001_squashed_0043_event_bill_to_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('admin_event', 'Can modify event'), ('bill_event', 'Can bill events'))},
        ),
        migrations.AlterField(
            model_name='event',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='ical',
            field=models.FilePathField(blank=True, match='*.ics', null=True, path='/virtualenv/ezreg3/include/ezreg/files'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='eventprocessor',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezreg.PaymentProcessor'),
        ),
        migrations.AlterField(
            model_name='organizeruserpermission',
            name='permission',
            field=models.CharField(choices=[('admin', 'Administer'), ('view', 'View registrations'), ('manage_processors', 'Manage payment processors')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='ezreg.Registration'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('INVALID_AMOUNT', 'Invalid Amount'), ('ERROR', 'Error')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ezreg.Event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, choices=[('REGISTERED', 'Registered'), ('PENDING_INCOMPLETE', 'Pending'), ('WAITLIST_PENDING', 'Pending from waitlist'), ('WAITLISTED', 'Waitlisted'), ('WAITLIST_INCOMPLETE', 'Waitlist- incomplete'), ('APPLIED_ACCEPTED', 'Application accepted'), ('APPLIED_DENIED', 'Application denied'), ('APPLIED', 'Applied'), ('APPLY_INCOMPLETE', 'Application- incomplete'), ('CANCELLED', 'Cancelled')], max_length=25, null=True),
        ),
    ]
