# Generated by Django 2.2.28 on 2023-02-10 16:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0003_auto_20220607_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ical',
            field=models.FilePathField(blank=True, match='*.ics', null=True, path='/usr/src/app/files'),
        ),
        migrations.AlterField(
            model_name='paymentprocessor',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
