# Generated by Django 2.2.28 on 2024-02-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0004_auto_20230210_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bill_to_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ical',
            field=models.FilePathField(blank=True, match='*.ics', null=True, path='/data/www/ezreg3/include/ezreg/files'),
        ),
    ]
