# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0026_auto_20180403_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('order',)},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([]),
        ),
    ]
