# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0027_auto_20180405_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
