# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 21:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0029_auto_20180618_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
