# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0030_organizer_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ezreg.Organizer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ezreg.PaymentProcessor'),
        ),
        migrations.AlterField(
            model_name='paymentprocessor',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_processors', to='ezreg.Organizer'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='ezreg.Price'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
