# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0031_auto_20180710_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ical',
            field=models.FilePathField(blank=True, match=b'*.ics', null=True, path=b'/virtualenv/ezreg/include/ezreg/files'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, choices=[(b'REGISTERED', b'Registered'), (b'PENDING_INCOMPLETE', b'Pending'), (b'WAITLIST_PENDING', b'Pending from waitlist'), (b'WAITLISTED', b'Waitlisted'), (b'WAITLIST_INCOMPLETE', b'Waitlist- incomplete'), (b'APPLIED_ACCEPTED', b'Application accepted'), (b'APPLIED_DENIED', b'Application denied'), (b'APPLIED', b'Applied'), (b'APPLY_INCOMPLETE', b'Application- incomplete'), (b'CANCELLED', b'Cancelled')], max_length=25, null=True),
        ),
    ]
