# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0032_auto_20181001_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ical',
            field=models.FilePathField(blank=True, match=b'*.ics', null=True, path=b'/virtualenvs/django-ezreg/include/ezreg/files'),
        ),
    ]
