# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0033_auto_20181108_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide_header',
            field=models.BooleanField(default=False),
        ),
    ]
