# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0034_event_hide_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tentative',
            field=models.BooleanField(default=False),
        ),
    ]
