# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-06 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0035_event_tentative'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ical',
            field=models.FilePathField(blank=True, match=b'*.ics', null=True, path=b'/virtualenv/ezreg/include/ezreg/files'),
        ),
    ]
