# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-15 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezreg', '0037_eventpage_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'pending', b'pending'), (b'cancelled', b'cancelled'), (b'completed', b'completed')], default=b'pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezreg.Registration')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'ordering': ('index', 'id')},
        ),
    ]
