# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-14 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0038_auto_20200114_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ('-requested',)},
        ),
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='ezreg.Registration'),
        ),
    ]
