# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0039_auto_20200214_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department_field',
            field=models.BooleanField(default=True),
        ),
    ]
