# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-05 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezreg', '0041_auto_20200605_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='billed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='billing_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
