# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-07 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezreg', '0042_auto_20200605_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bill_to_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
